name: Something Dark
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#737b88'
    - '#c09c8c'
    - '#fffb4a'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3245419836603105
  rhythmicContrast: 0.75
purpose: []
