name: Something Dark
favicon: null
layout_spectrum: 0.2320635428186506
typography_spectrum: 0.5287761557847261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14766809903085232
  lightness: 0.32585952151566744
  saturation: 0.3245419836603105
  rhythmicContrast: 0.39538475149311125
purpose: []
